### ISSUE TITLE
'can't dup Fixnum' error when using display method on fixnum

### ISSUE THREAD

**Issue by banister** [luislavena/win32console#11]
```
irb(main):001:0> 5.display
5=> nil
irb(main):002:0> require 'win32console'
=> true
irb(main):003:0> 5.display
#<Class:0x1450068>: can't dup Fixnum
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0-x86-mingw32/
lib/Win32/Console/ANSI.rb:149:in `dup'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0-x86-mingw32/
lib/Win32/Console/ANSI.rb:149:in `_PrintString'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0-x86-mingw32/
lib/Win32/Console/ANSI.rb:137:in `block in write'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0-x86-mingw32/
lib/Win32/Console/ANSI.rb:137:in `each'
        from C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0-x86-mingw32/
lib/Win32/Console/ANSI.rb:137:in `write'
        from (irb):3:in `display'
        from (irb):3
        from C:/Ruby192/bin/irb:12:in `<main>'
irb(main):004:0>
```

**Comment by luislavena** [comment]
Hello,

Thank you for your report, however a notice has been put on README with indications about the project:

https://github.com/luislavena/win32console/blob/master/README.txt#L7-14

No further development will be performed due lack of resources. If you're willing to take ownership of the project, please say so.

Thank you and apologies for not being more helpful.
