### ISSUE TITLE
Strange issue with irb and Exception name

### ISSUE THREAD

**Issue by lboulard** [luislavena/win32console#7]
Without win32console:

```
irb(main):001:0> foo
NameError: undefined local variable or method `foo' for main:Object
    from (irb):1
    from D:/Ruby192/bin/irb:12:in `<main>'
```

With win32console:

```
irb(main):001:0> foo
#<Class:0x15799b0>: undefined local variable or method `foo' for main:Object
    from (irb):1
    from D:/Ruby192/bin/irb:12:in `<main>'
```

I tried also other versions for ruby install (1.8.6p398, 1.8.7p302, 1.9.1p430) and get same issue.

**Comment by lboulard** [comment]
Another way to see the issue:

```
D:\Documents>irb -f
irb(main):002:0> foo
NameError: undefined local variable or method `foo' for main:Object
    from (irb):2
    from D:/Ruby192/bin/irb:12:in `<main>'
irb(main):003:0> require 'win32console'
=> true
irb(main):004:0> include Win32::Console::ANSI
=> Object
irb(main):005:0> foo
#<Class:0xf59940>: undefined local variable or method `foo' for main:Object
    from (irb):5
    from D:/Ruby192/bin/irb:12:in `<main>'
```

**Comment by luislavena** [comment]
Don't include Win32::Console::ANSI

Is not meant to be included.

**Comment by lboulard** [comment]
Thanks. but ...

```
D:\Documents>irb -f
irb(main):001:0> foo
NameError: undefined local variable or method `foo' for main:Object
    from (irb):1
    from D:/Ruby192/bin/irb:12:in `<main>'
irb(main):002:0> require 'win32console'
=> true
irb(main):003:0> foo
#<Class:0x126de48>: undefined local variable or method `foo' for main:Object
    from (irb):3
    from D:/Ruby192/bin/irb:12:in `<main>'
```

**Comment by luislavena** [comment]
Sorry, no case:

<pre><code>
C:\Users\Luis\Desktop>ruby -ve "puts foo"
ruby 1.8.7 (2010-08-16 patchlevel 302) [i386-mingw32]
-e:1: undefined local variable or method `foo' for main:Object (NameError)

C:\Users\Luis\Desktop>ruby -rrubygems -ve "require 'win32console'; puts foo"
ruby 1.8.7 (2010-08-16 patchlevel 302) [i386-mingw32]
-e:1: undefined local variable or method `foo' for main:Object (NameError)
</code></pre>


Dunno what irb is doing, but win32console is not including itself into Object

**Comment by luislavena** [comment]
Hmn, perhaps is associated with this?

http://github.com/luislavena/win32console/blob/master/lib/Win32/Console.rb

You could have a valid case due that random include.

Will see what can be done. it is a bug that only shows in IRB.

**Comment by lboulard** [comment]
After raising exception in buggy code and forcing inclusion of win32console. I confirm that this happens only in irb.

```
C:\Users\lboulard>irb -d -f -rwin32console
Exception `LoadError' at <internal:lib/rubygems/custom_require>:29 - no such file to load -- win32console
Exception `LoadError' at <internal:lib/rubygems/custom_require>:29 - no such file to load -- rubygems/defaults/ruby
Exception `LoadError' at <internal:lib/rubygems/custom_require>:37 - no such file to load -- rubygems/defaults/ruby
C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0/lib/Win32/Console/ANSI.rb:154: warning: duplicated when clause is ignored
Exception `Errno::ENOENT' at C:/Ruby192/lib/ruby/site_ruby/1.9.1/rbreadline.rb:2099 - No such file or directory - C:/Users/lboulard/.inputrc
Exception `Errno::ENOENT' at C:/Ruby192/lib/ruby/site_ruby/1.9.1/rbreadline.rb:2099 - No such file or directory - C:/etc/inputrc
Exception `Errno::ENOENT' at C:/Ruby192/lib/ruby/site_ruby/1.9.1/rbreadline.rb:2099 - No such file or directory - C:/Users/lboulard/_inputrc
irb(main):001:0> foo
Exception `NameError' at (irb):1 - undefined local variable or method `foo' for main:Object
Exception `NameError' at C:/Ruby192/lib/ruby/1.9.1/irb/workspace.rb:80 - undefined local variable or method `foo' for main:Object
#<Class:0x2f83ba8>: undefined local variable or method `foo' for main:Object
    from (irb):1
    from C:/Ruby192/bin/irb:12:in `<main>'
```

This is the line `case $4` in current source code of ANSI.rb.

**Comment by lboulard** [comment]
Found that this is related to print with class method:

```
irb(main):004:0> print Object.class
#<Class:0x31bb8f8>=> nil
irb(main):005:0> puts Object.class
Class
```

**Comment by luislavena** [comment]
More details:

<pre><code>
irb(main):003:0> print
nil=> nil
irb(main):004:0> puts

=> nil
</code></pre>

**Comment by lboulard** [comment]
Seems this is the path to dig: 

```
irb(main):001:0> print
Exception `TypeError' at C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0/lib/Win32/Console/ANSI.rb:149 - can't dup NilClass
Exception `TypeError' at C:/Ruby192/lib/ruby/1.9.1/irb/workspace.rb:80 - can't dup NilClass
#<Class:0x307f9f8>: can't dup NilClass
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0/lib/Win32/Console/ANSI.rb:149:in `dup'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0/lib/Win32/Console/ANSI.rb:149:in `_PrintString'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0/lib/Win32/Console/ANSI.rb:137:in `block in write'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0/lib/Win32/Console/ANSI.rb:137:in `each'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/win32console-1.3.0/lib/Win32/Console/ANSI.rb:137:in `write'
    from (irb):1:in `print'
    from (irb):1
    from C:/Ruby192/bin/irb:12:in `<main>'
```

**Comment by lboulard** [comment]
without win32console, I get:

```
irb(main):001:0> print
=> nil
```

which is different of your output:

```
irb(main):003:0> print
nil=> nil
```

**Comment by lboulard** [comment]
Sir,

I found that:

http://github.com/luislavena/win32console/blob/master/lib/Win32/Console/ANSI.rb

line 147, changing `t.dup.to_s` to `t.to_s.dup` fixed my issue.

**Comment by lboulard** [comment]
Final changes are in this patch (win32console version from gem installation):

http://gist.github.com/551383
